// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // The Prisma CLI (migrate, generate, studio) only supports a single `url`
    // here - no directUrl field in this Prisma version. So: prefer the direct/
    // unpooled connection for CLI/migration use when one is configured
    // (Vercel's Neon integration sets DATABASE_URL_UNPOOLED automatically).
    // The app's own runtime client (src/lib/prisma.ts) reads DATABASE_URL
    // directly and independently, so it keeps using the pooled connection
    // regardless of what's set here.
    url: process.env["DATABASE_URL_UNPOOLED"] || process.env["DATABASE_URL"],
  },
});
